[project]
name = "twiga-warehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dagster>=1.13.7",
    "dagster-webserver>=1.13.7",
    "langchain-core>=1.4.0",
    "langchain-google-genai>=4.2.4",
    "langchain-openai>=1.2.2",
    "langchain-text-splitters>=1.1.2",
    "langchain-unstructured>=1.0.1",
    "mistralai==1.9.11",
    "openai>=2.38.0",
    "pgvector>=0.4.2",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.1",
    "pymupdf>=1.27.2.3",
    "pymupdf4llm<0.0.20",
    "pypdf>=6.12.2",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.50",
    "sqlmodel>=0.0.38",
    "together>=2.16.0",
    "tqdm>=4.67.3",
    "typer>=0.26.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pytest>=8.2.0",
]
